# Generated by Django 3.1.5 on 2021-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='staff-pics/default.jpg', upload_to='staff-pics'),
        ),
    ]
