# Generated by Django 3.1.5 on 2021-02-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210210_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='staff-pics/test.jpg', upload_to='static/staff-pics'),
        ),
    ]
