# Generated by Django 3.1.5 on 2021-04-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210405_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1200)),
                ('dates', models.JSONField()),
                ('logo_URL', models.URLField()),
                ('about', models.CharField(max_length=1200)),
                ('testimonial', models.CharField(max_length=1200)),
                ('video_URL', models.URLField()),
                ('faq', models.JSONField()),
            ],
        ),
    ]
