# Generated by Django 3.1.5 on 2021-04-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='logo_URL',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='video_URL',
            field=models.CharField(max_length=200),
        ),
    ]
