# Generated by Django 3.1.5 on 2021-04-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20210408_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='logo_URL',
            new_name='logo_path',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='video_URL',
            new_name='video_path',
        ),
    ]
