# Generated by Django 3.1.5 on 2021-04-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='mysite/static/staff-pics/default.jpg', upload_to='mysite/static/staff-pics'),
        ),
    ]
