# Generated by Django 3.1.5 on 2021-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20210415_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default='staff-pics/default.jpg', upload_to='staff-pics'),
        ),
    ]
