# Generated by Django 3.1.5 on 2021-04-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_center_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
