# Generated by Django 3.1.5 on 2021-05-07 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210422_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('description', models.CharField(max_length=1200)),
                ('tags', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='Virtual', max_length=200)),
            ],
        ),
    ]
