# Generated by Django 3.1.5 on 2021-05-25 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_dosearticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoseArticle',
        ),
    ]
