# Generated by Django 3.1.5 on 2021-05-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_delete_dosearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydose',
            name='about',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='dates',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='faq',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='logo_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='testimonial',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='video_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
