# Generated by Django 3.1.5 on 2021-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20210524_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydose',
            name='about',
        ),
        migrations.RemoveField(
            model_name='dailydose',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='dailydose',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='dailydose',
            name='logo_path',
        ),
        migrations.RemoveField(
            model_name='dailydose',
            name='testimonial',
        ),
        migrations.AddField(
            model_name='dailydose',
            name='first_article_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fourth_article_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='grade_band',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='key_question',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_article_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='third_article_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
