# Generated by Django 3.1.5 on 2021-05-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_dailydose_first_panel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydose',
            old_name='first_panel',
            new_name='first_panel_image',
        ),
        migrations.RemoveField(
            model_name='dailydose',
            name='video_path',
        ),
        migrations.AddField(
            model_name='dailydose',
            name='first_video_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_panel_image',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_video_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
