# Generated by Django 3.1.5 on 2021-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20210526_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydose',
            name='first_image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
