# Generated by Django 3.1.5 on 2021-05-26 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20210526_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydose',
            name='location',
        ),
    ]
