# Generated by Django 3.1.5 on 2021-06-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_remove_dailydose_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumb_photo',
            field=models.ImageField(default='staff-pics/default.jpg', upload_to='programs'),
        ),
    ]
