# Generated by Django 3.1.5 on 2021-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20210611_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('N', 'CCEE in the News'), ('M', 'Media Release'), ('O', 'Other')], default='N', max_length=2),
        ),
    ]
