# Generated by Django 3.1.5 on 2021-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20210611_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='thumb_photo',
            field=models.ImageField(blank=True, default='staff-pics/default.jpg', upload_to='programs'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb_photo',
            field=models.ImageField(blank=True, default='staff-pics/default.jpg', upload_to='programs'),
        ),
    ]
