# Generated by Django 3.1.5 on 2021-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20210611_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='html_content',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='show_html_content',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
