# Generated by Django 3.1.5 on 2021-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0035_auto_20210611_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_testimonial',
            field=models.BooleanField(default=True),
        ),
    ]
