# Generated by Django 3.1.5 on 2021-06-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_program_show_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='program',
            field=models.CharField(max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
