# Generated by Django 3.1.5 on 2021-06-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_directors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
    ]
