# Generated by Django 3.1.5 on 2021-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
