# Generated by Django 3.1.5 on 2021-06-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_director_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='dates',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='program',
            name='faq',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='logo_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='testimonial',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='program',
            name='video_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
