# Generated by Django 3.1.5 on 2021-06-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_auto_20210612_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='photo_path',
            field=models.ImageField(blank=True, default='staff-pics/default.jpg', upload_to='programs'),
        ),
    ]
