# Generated by Django 3.1.5 on 2021-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_program_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_video',
            field=models.BooleanField(default=True),
        ),
    ]
