# Generated by Django 3.1.5 on 2021-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_program_show_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='show_faq',
            field=models.BooleanField(default=True),
        ),
    ]
