# Generated by Django 3.1.5 on 2021-06-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_program_show_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='logo_path',
            field=models.ImageField(blank=True, default='staff-pics/default.jpg', upload_to='programs'),
        ),
    ]
