# Generated by Django 3.1.5 on 2021-06-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_auto_20210612_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1200),
        ),
        migrations.AlterField(
            model_name='event',
            name='program',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_url',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
