# Generated by Django 3.1.5 on 2021-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20210612_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='grade_level',
            field=models.CharField(choices=[('K', 'K-12th'), ('N', '9th-12th'), ('S', '6th-12th'), ('I', 'K-8th'), ('E', 'Educator')], default='K', max_length=2),
        ),
    ]
