# Generated by Django 3.1.5 on 2021-06-13 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20210612_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
