# Generated by Django 3.1.5 on 2021-06-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_remove_event_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo_path', models.ImageField(blank=True, default='staff-pics/default.jpg', upload_to='programs')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='banner_photo',
            field=models.ImageField(blank=True, default='programs/CCEE_in_the_News.png', upload_to='programs'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumb_photo',
            field=models.ImageField(blank=True, default='programs/CCEE_in_the_News.png', upload_to='programs'),
        ),
    ]
