# Generated by Django 3.1.5 on 2021-06-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_auto_20210616_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='banner_photo',
            field=models.ImageField(blank=True, default='programs/CCEE_in_the_News.png', upload_to='programs'),
        ),
    ]
