# Generated by Django 3.1.5 on 2021-06-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0051_program_banner_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='banner_photo',
            field=models.ImageField(blank=True, default='', upload_to='programs'),
        ),
    ]
