# Generated by Django 3.1.5 on 2021-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_auto_20210720_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydose',
            name='second_video_path',
        ),
        migrations.AlterField(
            model_name='dailydose',
            name='first_image_path',
            field=models.ImageField(blank=True, default='', upload_to='programs'),
        ),
        migrations.AlterField(
            model_name='dailydose',
            name='second_panel_image',
            field=models.ImageField(blank=True, default='', upload_to='programs'),
        ),
    ]
