# Generated by Django 3.1.5 on 2021-07-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0057_auto_20210726_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailydose',
            old_name='first_image_path',
            new_name='first_image',
        ),
        migrations.RenameField(
            model_name='dailydose',
            old_name='second_image_path',
            new_name='second_image',
        ),
    ]
