# Generated by Django 3.1.5 on 2021-07-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0061_auto_20210726_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydose',
            name='first_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AlterField(
            model_name='dailydose',
            name='second_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
    ]
