# Generated by Django 3.1.5 on 2021-07-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0062_auto_20210726_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydose',
            name='key_question_secondary',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
