# Generated by Django 3.1.5 on 2021-07-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0063_dailydose_key_question_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydose',
            name='fifth_resource_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fifth_resource_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fifth_resource_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fifth_resource_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='first_resource_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='first_resource_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='first_resource_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fourth_resource_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fourth_resource_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='fourth_resource_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_resource_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_resource_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='second_resource_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='show_fifth_resource',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='show_first_resource',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='show_fourth_resource',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='show_second_resource',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='show_sixth_resource',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='show_third_resource',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='sixth_resource_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='sixth_resource_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='sixth_resource_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='sixth_resource_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='third_resource_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='third_resource_image',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AddField(
            model_name='dailydose',
            name='third_resource_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
