# Generated by Django 3.1.5 on 2021-07-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0064_auto_20210726_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydose',
            name='tags',
            field=models.CharField(blank=True, default=' ', max_length=200),
        ),
    ]
