# Generated by Django 3.1.5 on 2021-07-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0065_auto_20210727_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydose',
            name='banner_photo',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
        migrations.AlterField(
            model_name='dailydose',
            name='tags',
            field=models.CharField(blank=True, default='Daily Dose', max_length=200),
        ),
    ]
