# Generated by Django 3.1.5 on 2021-07-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0066_auto_20210727_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydose',
            name='banner_photo',
            field=models.ImageField(blank=True, default='programs/blank.png', upload_to='programs'),
        ),
    ]
