# Generated by Django 3.1.5 on 2021-07-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0071_auto_20210727_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydose',
            name='banner_photo',
            field=models.ImageField(blank=True, default='blank.png', upload_to='programs'),
        ),
    ]
