# Generated by Django 3.1.5 on 2021-07-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0072_auto_20210727_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydose',
            name='banner_photo',
            field=models.ImageField(default='blank.png', upload_to='programs'),
        ),
    ]
