# Generated by Django 3.1.5 on 2021-11-09 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0075_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
