# Generated by Django 3.1.5 on 2022-02-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0076_program_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='grade_range',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
