# Generated by Django 3.1.5 on 2021-10-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0077_auto_20211015_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
