# Generated by Django 3.1.5 on 2021-10-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0078_auto_20211015_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
