# Generated by Django 3.1.5 on 2021-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0080_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(default='12:00 PM', max_length=8),
        ),
    ]
